### ISSUE TITLE
Please remove schema registry dependency from service-manager

### ISSUE THREAD

**Issue by adriancole** [hypertrace/pinot#39]
While no issue has been raised here, yet, schema registry is not required at runtime here, especially in service-manager.

Can we please make foreground what is holding up the migration off schema registry for the service-manager image?

**Comment by adriancole** [comment]
https://github.com/hypertrace/hypertrace/issues/48 depends on this

**Comment by kotharironak** [comment]
Resolved as part of this PR : https://github.com/hypertrace/hypertrace/pull/75

**Comment by adriancole** [comment]
verified this works!
