### ISSUE TITLE
pinot servers restarts multiple time during upgrade

### ISSUE THREAD

**Issue by ravisingal** [hypertrace/pinot#46]
pinot server take a lot of time during startup (it loads all the segments of the server) during which time liveness probe fails and restart the pod. This happens multiple times before the pod is in ready state.

Options:
1. Change the liveness to check the tcp socket port instead of http url. HTTP port takes time the requests. It waits for all the segments to load. Readiness probe will continue to use http url for probe. this will ensure  that during rolling restart, the next server is restarted only when the first server startup has completed successfully.
2. Increase the initialDelaySeconds/failureThreshold of liveness probe to allow the startup to complete without restart. This time increases with the number of segments hosted on the server.
3. Remove the liveness probe from server statefulset. The default helm chart from Apache Pinot does not include livenessProbe/readinessProbe: https://github.com/apache/incubator-pinot/blob/master/kubernetes/helm/pinot/templates/server/statefulset.yml

**Comment by kotharironak** [comment]
@ravisingal can we close this?

**Comment by kotharironak** [comment]
closing this.
